# Generated by Django 5.2.8 on 2026-01-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_file_is_starred_file_is_trashed_file_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
