# Generated by Django 5.2.8 on 2026-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_file_shared_with_folder_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
