# 1. ZOOKEEPER (Kafka'nın Yöneticisi)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: quay.io/debezium/zookeeper:2.4
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
# 2. APACHE KAFKA (Veri Borusu)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: quay.io/debezium/kafka:2.4
        env:
        - name: ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
---
# 3. DEBEZIUM CONNECT (İşçi Sınıfı - PG'den alıp ES'e atacak)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
      - name: debezium-connect
        # Debezium'un Elasticsearch eklentisi olan özel imajı
        image: quay.io/debezium/connect:2.4
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "my_connect_configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "my_connect_offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "my_connect_statuses"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: debezium
spec:
  selector:
    app: debezium
  ports:
    - port: 8083
      targetPort: 8083